# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

# PROPRIEDADES DA PÁGINA
encoding: utf-8
name: PHP-PB
baseurl: "/"
url: http://php-pb.net/
description: Comunidade PHP na Paraíba

permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: 'page:num'

# MENU DE NAVEGAÇÃO
navigation:
- text: início
  url: '/'
- text: palestras
  url: '/palestras'
- text: vagas de emprego
  url: '/vagas'
- text: hangouts
  url: '/hangouts'

# Grunt handles images and assets.
exclude: ['images', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
markdown: kramdown
pygments: true
